.\"Preocess this file with
.\"groff -man -Tascii foo.1
.\"
.TH ioup 1
.SH NAME 
ioup \- IOPaste client
.SH SYNOPSIS
.B ioup [-l] [-r] 
.B [
.I file
.B ]
.SH DESCRIPTION
.B ioup
is a commandline paste client for pub.iotek.org written in C. 
It uses libcurl to interpret file extenstions;
if no file extenstion is given or it is unrecognised,
.B ioup 
will upload it like a text/binary file. So make sure that your file always contains the correct 
suffix!

.B ioup reads the shell variable IOUP_TOKEN, so make sure you set it.
.SH OPTIONS
.IP "-l" 
.B list all files you've alredy pasted on IOPaste
.IP "-r file"
.B remove the given file in the format: p/RAnD0m
.SH EXAMPLES
.IP "$ ioup yourfile"
.B \- uploads an existing file from a local drive
.IP "$ ioup < yourfile" 
.B \- same as above
.IP "$ ioup -l "
.B \- lists all your uploaded files. You can use this if you want to remove some files
.IP "$ ioup -r p/RAnD0m" 
.B \- this removes the file pub.iotek.org/p/RAnD0m
.IP "$ dmesg | tail -n4 | ioup"
.B \- used this way, ioup will read directy from STDIN and creates your file on pub.iotek.org itself
.SH BUGS
.B Bugs? There are no bugs in this Software. It was written through the power of slienz.
.SH AUTHOR
.IP "a dead cat <dcat at iotek dot org>"
.IP "Danny Svensson <neuromatic at archlinux dot info>"
.SH SEE ALSO
.BR libcurl(3)
